<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130510083351 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE department ADD faculty_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE department ADD CONSTRAINT FK_8240E25A680CAB68 FOREIGN KEY (faculty_id) REFERENCES Faculty (id)");
        $this->addSql("CREATE INDEX IDX_8240E25A680CAB68 ON department (faculty_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE Department DROP FOREIGN KEY FK_8240E25A680CAB68");
        $this->addSql("DROP INDEX IDX_8240E25A680CAB68 ON Department");
        $this->addSql("ALTER TABLE Department DROP faculty_id");
    }
}
